@startuml
title Casual Coding Member Directory - 2024-12-15

participant Browser
participant App
participant Passport #lightgreen
participant "Mongo\nmySession" as MySession #lightblue
participant "Mongo\nusers" as Users #lightblue
participant "Mongo\nprojects" as Projects #lightblue

activate Browser

== POST /submit == 
Browser -> App: POST /submit\n- email\n- project\n- percent_done\n- description
activate App
'MIDDLEWARE
App -> Passport: ensureAuthenticated
activate Passport
Passport -> Passport: get user data from req
note over Passport: checking for an active session
Passport -> MySession: req.isAuthenticated()\n- user
activate MySession
MySession --> Passport: response
deactivate MySession
Passport --> App: response
deactivate Passport
alt user is not authenticated
  App --> Browser: redirect to /login
else user is authenticated
  App -> Users: find user by ID
  activate Users
  Users --> App: response
  deactivate Users
  alt found user
    App -> Users: submit project:\n- email\n- project\n- percent_done\n- description
    activate Users
    Users --> App: OK
    deactivate Users
    App --> Browser: redirect to /project_tables
  else user not found
    note over App: TODO Handle this scenario
    App --> Browser: redirect to /project_tables
  else error
    App -> App: log the error
    App --> Browser: error message
    deactivate App
  end
end


deactivate Browser
@enduml